#ifndef GPIODEFS_H
#define GPIODEFS_H

#ifdef __cplusplus
  extern "C" {
#endif

/*
File auto-generated by m-gen v1.0                  
   (see https://github.com/Leopardus4/m-gen )     

DO NOT EDIT THIS FILE!                            
Please edit apprioritate .gm file and run m-gen   

*/

/*

This file contains macros for access LED1.
To change gpio to another, edit .gm file and run m-gen

*/




//------------------------------------------------------------------------//

/* LED1 - PD3 - active low output 
	 	Torch emulator...
 */

#define LED1_asOutput()   do{DDRD |= (1<<PD3);} while(0)

#define LED1_On()         do{PORTD &= ~(1<<PD3);} while(0)

#define LED1_Off()        do{PORTD |= (1<<PD3);} while(0)


//------------------------------------------------------------------------//


#ifdef __cplusplus
  }
#endif

#endif    // GPIODEFS_H
